### PR TITLE
Update version to 1.0.0 (prepare for release)

### PR DESCRIPTION
**Pull request by reta**
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>

### Description
Update version to 1.0.0 (prepare for release)

### Issues Resolved
N/A

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
@dblock please take a look when you have time

**Comment by reta** [comment]
@dblock please take a look when you have time

**Comment by bbarani** [comment]
@wbeckler @dlvenable please let us know if this needs to wait until security reviews are completed.

**Comment by exZStas** [comment]
Just wondering: any progress on security reviews?

**Comment by nsanaia** [comment]
Any thoughts approximately when the release will be done? Thanks

**Comment by reta** [comment]
@dblock could you please help with [security reviews](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#security-reviews), not sure what it entails?

**Comment by wbeckler** [comment]
Security reviews are successfully completed and this can be approved.

**Comment by wbeckler** [comment]
@dblock would you be willing to approve?

**Comment by reta** [comment]
@gaiksaya could you please enable the release job on Jenkins? https://build.ci.opensearch.org/job/spring-data-opensearch-release/, thank you

**Comment by gaiksaya** [comment]
> @gaiksaya could you please enable the release job on Jenkins? https://build.ci.opensearch.org/job/spring-data-opensearch-release/, thank you

Done!
cc: @bbarani

**Comment by reta** [comment]
> > @gaiksaya could you please enable the release job on Jenkins? https://build.ci.opensearch.org/job/spring-data-opensearch-release/, thank you

@gaiksaya  I pushed the pre-release 0.2.0 [1] but Jenkins job didn't trigger [2], mind please taking a look?

[1] https://github.com/opensearch-project/spring-data-opensearch/releases/tag/0.2.0
[2] https://build.ci.opensearch.org/job/spring-data-opensearch-release/

**Comment by gaiksaya** [comment]
@reta, The workflow is based on draft release as a trigger which is generated using [release-drafter.yml](https://github.com/opensearch-project/spring-data-opensearch/blob/main/.github/workflows/release-drafter.yml) . I see it is marked as pre-release. You should just push the tag and let it do its thing. Once release is published, you can make is pre-release.

**Comment by reta** [comment]
> @reta, The workflow is based on draft release as a trigger which is generated using [release-drafter.yml](https://github.com/opensearch-project/spring-data-opensearch/blob/main/.github/workflows/release-drafter.yml) . I see it is marked as pre-release. You should just push the tag and let it do its thing. Once release is published, you can make is pre-release.

@gaiksaya  redid the tag [1] + release [2] - nothing is happening 

[1] https://github.com/opensearch-project/spring-data-opensearch/tagsdata-opensearch/releases/tag/0.2.0
[2] https://github.com/opensearch-project/spring-

**Comment by gaiksaya** [comment]
Taking a look!

**Comment by gaiksaya** [comment]
@reta Can you confirm that 0.2.0 tag is based on main? I'll try triggering it from my end
Thanks!

**Comment by reta** [comment]
> @reta Can you confirm that 0.2.0 tag is based on main? I'll try triggering it from my end Thanks!

@gaiksaya yes, it does, latest commit to `main`

**Comment by reta** [comment]
> Its running: https://build.ci.opensearch.org/job/spring-data-opensearch-release/9/. I did not push the tag just deleted the GH release and re-ran the release-drafter workflow. Once the release is successful, the release is auto-published on release. I believe, before it can trigger the workflow the release was published by you :D The idea is GH release should be published on GH only when the components are out there In this case on maven.

Oh I see now, so it does not work when (pre)release is created using Github, understood, thank you!

**Comment by wbeckler** [comment]
What's the next step to get this released as a 1.0?

**Comment by reta** [comment]
> What's the next step to get this released as a 1.0?

@wbeckler just an approval from one of the maintainers (@dblock , @dlvenable ), I cannot merge the pull request otherwise

**Comment by wbeckler** [comment]
@dblock can you take a look? Appsec review is a done.

**Comment by wbeckler** [comment]
@dlvenable are you okay to approve? The appsec review is complete.

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
Done! Sorry for the delay.

**Pull request merged**
