### PR TITLE
Update README.md with 1.0.0 release

### PR DESCRIPTION
**Pull request by reta**
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>

### Description
Update README.md with 1.0.0 release

### Issues Resolved
https://github.com/opensearch-project/spring-data-opensearch/releases/tag/1.0.0

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
@dblock needs your approval please

**Comment by reta** [comment]
@dlvenable @dblock please approve

**Comment by reta** [comment]
@wbeckler may need you help here :-)

**Comment by reta** [comment]
@dlvenable @dblock please approve

**Comment by wbeckler** [comment]
@dlvenable @dblock future progress of this application is in your hands

**Pull request merged**
