### PR TITLE
Dependency updates (Spring, JUnit, OpenSearch)

### PR DESCRIPTION
**Pull request by reta**
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>

### Description
Dependency updates (Spring, JUnit, OpenSearch)

### Issues Resolved
N/A

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by reta** [comment]
@dblock @dlvenable please take a look folks

**Comment by reta** [comment]
@gaiksaya pushing my luck here :-) but may I ask you to approve this one as well, not related to the build but a few dependency update so I could release 0.2.0, thank you!

**Comment by bbarani** [comment]
@wbeckler @dblock Are we good to release 0.2.0? Can you please confirm if there are any pending reviews?

**Comment by reta** [comment]
> @wbeckler @dblock Are we good to release 0.2.0? Can you please confirm if there are any pending reviews?

@bbarani just to clarify for 0.2.0 - only dependency updates and one of the module names were corrected (reason to release to fix thayt), thank you

**Comment by gaiksaya** [comment]
Hi @reta ,
I know this is just dependency updates but would live to the experts (maintainers of the repository) to make the call. :)

Also FYI, the release workflow for spring data is disabled for now https://build.ci.opensearch.org/job/spring-data-opensearch-release/ until we get a go ahead from the security review process. 
@dblock @wbeckler Can add more. Just let us know when security review is done and we can then enable it. 
Thanks!

**Review by dlvenable — APPROVED** [review]

**Pull request merged**
